### PR TITLE
Image and file convertion

### PR DESCRIPTION
**Pull request by Shooteger**
The images in the README files will be displayed, when the branch gets merged. They seem broken now because the paths are not matching, the paths are set for production main branch.

### CODE REVIEW

**Comment by Shooteger** [comment]
Addressing issue 9: https://github.com/girliemac/a-picture-is-worth-a-1000-words/issues/9

**Comment by JGonzalvoZipDev** [comment]
Nice!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

**Comment by girliemac** [comment]
Thank you! I made some changes without noticing this PR! So let me resolve them first.

**Comment by Shooteger** [comment]
@girliemac Ready for merge

**Comment by girliemac** [comment]
Omg, sorry about taking so so long to merge 🤦‍♀️

**Comment by Shooteger** [comment]
> Omg, sorry about taking so so long to merge 🤦‍♀️

Just 1 and 1/2 years XD funny, I thought about this PR 2 days ago.

**Pull request merged**
